# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: rancher
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: production
#   source:
#     path: rancher/chart
#     repoURL: https://github.com/rancher/rancher.git
#     targetRevision: HEAD
#   destination:
#     namespace: cattle-system
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#       - CreateNamespace=true
